name: CD

on:
  push:
    branches:
      - main
      - api
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Login to GHCR
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4.3.0
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha,enable=true,priority=100,prefix=shaF-,suffix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-beta:
    name: deploy fintlabs-no to aks-beta-fint-2021-11-23
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: read
      packages: write
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      ORG: fintlabs-no
      CLUSTER: aks-beta-fint-2021-11-23
      ENVIRONMENT: beta   # derived from cluster name
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Get resource group name
        uses: actions/github-script@v6
        id: resource-group
        with:
          script: return `rg-aks-${process.env.ENVIRONMENT}`
          result-encoding: string

      - name: Bake manifests with Kustomize
        id: bake
        uses: azure/k8s-bake@v2.4
        with:
          renderEngine: 'kustomize'
          kustomizationPath: 'kustomize/overlays/${{ env.ENVIRONMENT }}/${{ env.ORG }}'

      - uses: azure/login@v1
        with:
          creds: "${{ secrets[format('AKS_{0}_FINT_GITHUB', env.ENVIRONMENT)] }}"

      - uses: azure/use-kubelogin@v1.1
        with:
          kubelogin-version: 'v0.0.26'

      - name: Set the target cluster
        uses: azure/aks-set-context@v3
        with:
          cluster-name: '${{ env.CLUSTER }}'
          resource-group: '${{ steps.resource-group.outputs.result }}'
          admin: 'true'
          use-kubelogin: 'true'

      - name: Deploy
        uses: azure/k8s-deploy@v4.9
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ needs.build-and-push.outputs.tags }}
          namespace: ${{ env.ORG }}

  deploy-api:
    name: deploy fintlabs-no to aks-api-fint-2022-02-08
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: read
      packages: write
    if: ${{ github.ref == 'refs/heads/api' }}
    env:
      ORG: fintlabs-no
      CLUSTER: aks-api-fint-2022-02-08
      ENVIRONMENT: api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Get resource group name
        uses: actions/github-script@v6
        id: resource-group
        with:
          script: return `rg-aks-${process.env.ENVIRONMENT}`
          result-encoding: string

      - name: Bake manifests with Kustomize
        id: bake
        uses: azure/k8s-bake@v2.4
        with:
          renderEngine: 'kustomize'
          kustomizationPath: 'kustomize/overlays/${{ env.ENVIRONMENT }}/${{ env.ORG }}'

      - uses: azure/login@v1
        with:
          creds: "${{ secrets[format('AKS_{0}_FINT_GITHUB', env.ENVIRONMENT)] }}"

      - uses: azure/use-kubelogin@v1.1
        with:
          kubelogin-version: 'v0.0.26'

      - name: Set the target cluster
        uses: azure/aks-set-context@v3
        with:
          cluster-name: '${{ env.CLUSTER }}'
          resource-group: '${{ steps.resource-group.outputs.result }}'
          admin: 'true'
          use-kubelogin: 'true'

      - name: Deploy
        uses: azure/k8s-deploy@v4.9
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ needs.build-and-push.outputs.tags }}
          namespace: ${{ env.ORG }}
